# Generated by Django 5.2.3 on 2025-06-30 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takvim.bolum')),
            ],
        ),
        migrations.CreateModel(
            name='Gozetmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takvim.bolum')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takvim.bolum')),
            ],
        ),
        migrations.CreateModel(
            name='Sinav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('saat', models.TimeField()),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takvim.ders')),
                ('gozetmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takvim.gozetmen')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takvim.salon')),
            ],
        ),
    ]
