# Generated by Django 5.2.3 on 2025-06-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takvim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinav',
            name='tur',
            field=models.CharField(choices=[('vize', 'Vize'), ('final', 'Final'), ('but', 'Bütünleme')], default='vize', max_length=10),
        ),
    ]
