# Generated by Django 4.2.23 on 2025-07-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takvim', '0002_sinav_tur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ders',
            name='donem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='takvim.donem'),
        ),
    ]
